# Generated by Django 4.2.1 on 2023-05-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.user')),
            ],
        ),
    ]
